### ISSUE TITLE
Trouble when using via CircleCI: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by kamilongus** [kroniak/alpine-ssh-client#2]
When I attach workspace to the image, I get the following error:

![image](https://user-images.githubusercontent.com/5605372/55005204-03bfe400-4ff5-11e9-82a9-0b8c15a82d46.png)

I found a possible solution to this problem here:
https://discuss.circleci.com/t/requesterror-x509-certificate-signed-by-unknown-authority-on-attaching-workspace-when-using-a-certain-job-image/28057

**Comment by kroniak** [comment]
@kamilongus hello. try new version of container with ca-certificates

**Comment by kamilongus** [comment]
@kroniak Thank you, now it works.
